### ISSUE TITLE
please set up prettier

### ISSUE THREAD

**Issue by KTibow** [importantimport/mcu-extra#5]
title

**Comment by kwaa** [comment]
~~If there is an update after that, I should set up eslint ([`@importantimport/eslint-config`](https://github.com/importantimport/config/tree/main/packages/eslint-config)), but not prettier.~~

I see that I have eslint set up. is there anything that only prettier can do?

**Comment by KTibow** [comment]
linting and formatting are different things
personally i prefer having consistently formatted code as it makes it easier to read code
of course it's up to you if you want to use it

**Comment by kwaa** [comment]
> linting and formatting are different things personally i prefer having consistently formatted code as it makes it easier to read code of course it's up to you if you want to use it

I do both linting and formatting in the ESLint configuration.

For more information, you can refer to antfu's article [Why I don't use Prettier](https://antfu.me/posts/why-not-prettier)

**Comment by KTibow** [comment]
huh
again, my personal belief is that prettier is faster and more consistent compared to using eslint rules, as [this article](https://typescript-eslint.io/linting/troubleshooting/formatting/) states, but it sounds like you're set on using eslint
